-- ALTERA O NIVEL DE BACKUP PARA    SIMPLE
ALTER DATABASE  teste
SET RECOVERY SIMPLE;  
GO  

-- LIMPA O LOG
DBCC SHRINKFILE ('teste_log', 1);  
GO  

-- ALTERA O NIVEL DE BACKUP   FULL
ALTER DATABASE  teste
SET RECOVERY FULL;  
GO
